server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://qcituzehodmaot:43caca8a900f9a083f2f803fc8f5321bf8d7c0b0cba5949d33fe76bd7ddeea3b@ec2-54-225-228-142.compute-1.amazonaws.com:5432/dcogbraij7978
    username: qcituzehodmaot
    password: 43caca8a900f9a083f2f803fc8f5321bf8d7c0b0cba5949d33fe76bd7ddeea3b
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander
  version: 1.0
