server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://qvbdtyyoparjcc:74a980d571a016115e0609f3938f01872e5b77e2e94bef412e6555e50251f5b0@ec2-52-0-114-209.compute-1.amazonaws.com:5432/df1dg97dje8lt5
    username: qvbdtyyoparjcc
    password: 74a980d571a016115e0609f3938f01872e5b77e2e94bef412e6555e50251f5b0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander
  version: 1.0
